version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres

volumes:
    db:
      driver: local
      driver_opts:
        type: none
        device: /data/postgres
        o: bind